/**
 * Migration: Create api_clients table
 * Tabel untuk menyimpan registered API clients yang bisa mengakses API Bridge
 */

exports.up = function(knex) {
  return knex.schema.createTable('api_clients', (table) => {
    // Primary Key
    table.increments('id').primary();
    
    // Client name/description
    table.string('name', 255).notNullable();
    table.text('description').nullable();
    
    // Registered API URL yang akan menggunakan API Bridge ini
    table.string('api_url', 500).notNullable();
    
    // Client credentials (generated by system)
    table.string('client_key', 255).notNullable().unique();
    table.string('client_secret', 255).notNullable();
    
    // Status
    table.boolean('is_active').defaultTo(true);
    
    // IP whitelist (optional, JSON array)
    table.jsonb('ip_whitelist').nullable();
    
    // Rate limiting (optional)
    table.integer('rate_limit_per_minute').defaultTo(100);
    table.integer('rate_limit_per_hour').defaultTo(1000);
    
    // Metadata
    table.text('notes').nullable();
    
    // Timestamps
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('last_used_at', { useTz: true }).nullable();
    
    // Indexes
    table.index(['client_key'], 'idx_api_clients_client_key');
    table.index(['api_url'], 'idx_api_clients_api_url');
    table.index(['is_active'], 'idx_api_clients_is_active');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('api_clients');
};

